### PR TITLE
added some sounds

### PR DESCRIPTION
**Pull request by CapsAdmin**
some samples taken from freesound.org

### CODE REVIEW

**Comment by TheJJ** [comment]
I fear your commit hast the wrong email attached, so it is not attributed to you. You can amend it to change the mail.

Also, we need to add you to the contributors list.
We have the copying.md file in the main openage folder, we should copy it into this repo and adapt it.
There you can be added, so we have a nice listing of all copyright holders.

I'll create the file soon™, you can also do it yourself if you like.

**Comment by CapsAdmin** [comment]
Sorry for taking so long but that should be done now.

**Comment by TheJJ** [comment]
Thanks, but unfortunately your commit email is still wrong :( Did you use `git config --global user.email` and `git commit --amend`?

**Comment by CapsAdmin** [comment]
Yeah. I had to do `git commit --amend --author="CapsAdmin <eliashogstvedt@gmail.com"` instead.

**Comment by TheJJ** [comment]
Thanks :)

**Pull request merged**
