### PR TITLE
[WIP] Asset placeholders

### PR DESCRIPTION
**Pull request by detrumi**
Continuation of #9 

- [x] Graphics
  - [x] Buildings
  - [x] Units
  - [x] Ship sails
  - [x] Trees and nature stuff
  - [x] Shadows, projectiles and unidentified things
- [ ] Sounds
- [ ] Interface (most important in-game graphics only)

As github doesn't handle lots of files in a commit well, you can browse the files [here](https://github.com/detrumi/openage-data/tree/5d0f3dc6a7142495549c4c6adc0a0e2f2e57d9a2/data/graphic)

### CODE REVIEW

**Comment by CapsAdmin** [comment]
Any progress on this? And if not (and you don't have the time), can you roughly explain how this was done so someone else could finish the rest?

**Comment by detrumi** [comment]
Ah, I kinda let this PR hanging, even though I didn't finish it. The files should still be around somewhere, let me check whether I can find it.

**Comment by detrumi** [comment]
Sadly, I can't find the files I was working with any more. Though I'm not interested at the moment to continue this, this is roughly how I did it:
- Look through the assets, they should have numbers associated with them
- Identify what each graphic shows, and try to categorize them
- Give each asset a name

For the categories, I grouped assets together, so that multiple assets from the same unit are together in the same directory. I also gave assets names based on some rules to try to keep them consistent. Some naming conventions like `<num>_<building>_<civilization>_<age>_<water/shadow/whatever>` or `gate_arabic_closed_ne_sw_shadow` are used to distinguish similar assets.

The graphics for units, objects etc. are mostly done, I think, though some misc stuff might need better categories at some point. But you should check that no numbers are missing (for the range of assets that are graphics, if I remember correctly).

Identifying sounds and interface stuff is probably harder, and it's a lot of busywork. It might also be better to get a textual list of assets and names first, instead of dumping a huge commit with empty files, which is kind of hard to work with.

**Comment by CapsAdmin** [comment]
I wasn't aware that this was a lot of manual work. 

The scheme you have is nice, id first, terminated by an underscore and then friendly/comment name afterwards. This should be easy for a program to parse while at the same time being user friendly if they want to browse and change assets from a file browser.

Since I'm redoing some sounds I can at least name the ones I've done. I'm thinking `12345_noname.todo` or `12345.todo` is fine for assets that haven't been identified.

**Comment by TheJJ** [comment]
I would recommend to sync the structure of the assets with the data tree, because our current plan was to mix assets and data definitions in a meaningful way (and not to have two separate directory trees). @heinezen and @mic-e are planning this. The draft of the file hierarchy is [here](https://pad.stusta.de/p/openage-file-hierarchy).

The main thing to consider is that we will have [`.sprite` files](https://pad.stusta.de/p/openage-sprite-format) that define one "look" of a unit (including all directions and animations). The `.sprite` file then references to one or more `.png` files that actually contain the image data.

Please have a look at the file hierarchy planning document. If you have any concerns/ideas/improvements, please share them so we can work out an optimal solution :)

**Pull request closed without merging**
